### ISSUE TITLE
trust anchors - verification of server certificate

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-conduit#31]
as discussed in #23, conduit should deliver some 'default' trust anchors. how is the best way to do so? It is a list of pem-encoded certificates -- should it install such a trust anchor file (if so, how do I tell the build system to install a resource and how do I access it at run-time (how do I find out what the complete path is)?
or should we inline these pem-encoded certificates into a .ml file and compile them into the binary/shared object?

**Comment by yomimono** [comment]
It seems that conduit currently doesn't have any mechanism for specifying or using trust anchors in TLS connections at all; see https://github.com/mirage/ocaml-conduit/blob/master/lib/conduit_mirage.ml#L290 , which disables authentication of the remote host for client connections with no way to request another behavior, even if the problem of knowing the trust anchors is already solved.

**Comment by hannesm** [comment]
@yomimono yes. I still don't have any clue how an API for conduit should look like. I can think of two scenarios:
- opportunistic encryption (like the www): use a set of curated CA certificates (somewhere hardcoded, so far I failed to create such a set)
- authenticated connection: the user provides their trust anchors explicitly (works great if you're in control of the system and know what you are doing / want to achieve) [another topic might be client authentication, but as far as I remember, conduit is off-topic there]

maybe for conduit the former is all needed, whereas if the latter is desired you use TLS explicitly!?

**Comment by yomimono** [comment]
I'd argue that the latter is needed in Conduit as well, as we have some libraries that expect to communicate on top of a conduit (e.g. Cohttp_mirage.Client) for which it might be desirable to have the latter behavior.

**Comment by hannesm** [comment]
@yomimono I do not object (I'm just not sure about the scope of conduit and the interface)

**Comment by dinosaure** [comment]
From my point of view, this issue become _orthogonal_ to `conduit` where TLS protocol (how to initialize it) is out of the core of `conduit` - however, we still provides `conduit-{async,lwt}-tls`. The way to initialize a `Tls.Config.client` is at the user's discretion and it's not the part of `conduit`. Then, the user is able to use this configuration to initialize a client.

By this way, the user is able to use default "trust anchors" - and this point should be done by complementary with [ca-certs](https://github.com/mirage/ca-certs).
